// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocolBuffers.proto

package com.protocol.buffers;

public final class TabularStructure {
    private TabularStructure() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface ColInformationOrBuilder extends com.google.protobuf.MessageOrBuilder {

        // optional string colName = 1;
        /**
         * <code>optional string colName = 1;</code>
         */
        boolean hasColName();

        /**
         * <code>optional string colName = 1;</code>
         */
        java.lang.String getColName();

        /**
         * <code>optional string colName = 1;</code>
         */
        com.google.protobuf.ByteString getColNameBytes();

        // optional string colType = 2;
        /**
         * <code>optional string colType = 2;</code>
         */
        boolean hasColType();

        /**
         * <code>optional string colType = 2;</code>
         */
        java.lang.String getColType();

        /**
         * <code>optional string colType = 2;</code>
         */
        com.google.protobuf.ByteString getColTypeBytes();
    }

    /**
     * Protobuf type {@code databases.ColInformation}
     */
    public static final class ColInformation extends com.google.protobuf.GeneratedMessage
            implements ColInformationOrBuilder {
        // Use ColInformation.newBuilder() to construct.
        private ColInformation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private ColInformation(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final ColInformation defaultInstance;

        public static ColInformation getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public ColInformation getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private ColInformation(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        bitField0_ |= 0x00000001;
                        colName_ = input.readBytes();
                        break;
                    }
                    case 18: {
                        bitField0_ |= 0x00000002;
                        colType_ = input.readBytes();
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.protocol.buffers.TabularStructure.internal_static_databases_ColInformation_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.protocol.buffers.TabularStructure.internal_static_databases_ColInformation_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.protocol.buffers.TabularStructure.ColInformation.class,
                            com.protocol.buffers.TabularStructure.ColInformation.Builder.class);
        }

        public static com.google.protobuf.Parser<ColInformation> PARSER = new com.google.protobuf.AbstractParser<ColInformation>() {
            @Override
            public ColInformation parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new ColInformation(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<ColInformation> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // optional string colName = 1;
        public static final int COLNAME_FIELD_NUMBER = 1;
        private java.lang.Object colName_;

        /**
         * <code>optional string colName = 1;</code>
         */
        @Override
        public boolean hasColName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string colName = 1;</code>
         */
        @Override
        public java.lang.String getColName() {
            java.lang.Object ref = colName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    colName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string colName = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString getColNameBytes() {
            java.lang.Object ref = colName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                colName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string colType = 2;
        public static final int COLTYPE_FIELD_NUMBER = 2;
        private java.lang.Object colType_;

        /**
         * <code>optional string colType = 2;</code>
         */
        @Override
        public boolean hasColType() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string colType = 2;</code>
         */
        @Override
        public java.lang.String getColType() {
            java.lang.Object ref = colType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    colType_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string colType = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString getColTypeBytes() {
            java.lang.Object ref = colType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                colType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            colName_ = "";
            colType_ = "";
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getColNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getColTypeBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getColNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getColTypeBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.ColInformation parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.protocol.buffers.TabularStructure.ColInformation prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code databases.ColInformation}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.protocol.buffers.TabularStructure.ColInformationOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_ColInformation_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_ColInformation_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.protocol.buffers.TabularStructure.ColInformation.class,
                                com.protocol.buffers.TabularStructure.ColInformation.Builder.class);
            }

            // Construct using
            // com.protocol.buffers.TabularStructure.ColInformation.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                colName_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                colType_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_ColInformation_descriptor;
            }

            @Override
            public com.protocol.buffers.TabularStructure.ColInformation getDefaultInstanceForType() {
                return com.protocol.buffers.TabularStructure.ColInformation.getDefaultInstance();
            }

            @Override
            public com.protocol.buffers.TabularStructure.ColInformation build() {
                com.protocol.buffers.TabularStructure.ColInformation result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.protocol.buffers.TabularStructure.ColInformation buildPartial() {
                com.protocol.buffers.TabularStructure.ColInformation result = new com.protocol.buffers.TabularStructure.ColInformation(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.colName_ = colName_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.colType_ = colType_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.protocol.buffers.TabularStructure.ColInformation) {
                    return mergeFrom((com.protocol.buffers.TabularStructure.ColInformation) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.protocol.buffers.TabularStructure.ColInformation other) {
                if (other == com.protocol.buffers.TabularStructure.ColInformation.getDefaultInstance())
                    return this;
                if (other.hasColName()) {
                    bitField0_ |= 0x00000001;
                    colName_ = other.colName_;
                    onChanged();
                }
                if (other.hasColType()) {
                    bitField0_ |= 0x00000002;
                    colType_ = other.colType_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.protocol.buffers.TabularStructure.ColInformation parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.protocol.buffers.TabularStructure.ColInformation) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // optional string colName = 1;
            private java.lang.Object colName_ = "";

            /**
             * <code>optional string colName = 1;</code>
             */
            @Override
            public boolean hasColName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string colName = 1;</code>
             */
            @Override
            public java.lang.String getColName() {
                java.lang.Object ref = colName_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    colName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string colName = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString getColNameBytes() {
                java.lang.Object ref = colName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    colName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string colName = 1;</code>
             */
            public Builder setColName(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                colName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string colName = 1;</code>
             */
            public Builder clearColName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                colName_ = getDefaultInstance().getColName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string colName = 1;</code>
             */
            public Builder setColNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                colName_ = value;
                onChanged();
                return this;
            }

            // optional string colType = 2;
            private java.lang.Object colType_ = "";

            /**
             * <code>optional string colType = 2;</code>
             */
            @Override
            public boolean hasColType() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string colType = 2;</code>
             */
            @Override
            public java.lang.String getColType() {
                java.lang.Object ref = colType_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    colType_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string colType = 2;</code>
             */
            @Override
            public com.google.protobuf.ByteString getColTypeBytes() {
                java.lang.Object ref = colType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    colType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string colType = 2;</code>
             */
            public Builder setColType(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                colType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string colType = 2;</code>
             */
            public Builder clearColType() {
                bitField0_ = (bitField0_ & ~0x00000002);
                colType_ = getDefaultInstance().getColType();
                onChanged();
                return this;
            }

            /**
             * <code>optional string colType = 2;</code>
             */
            public Builder setColTypeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                colType_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:databases.ColInformation)
        }

        static {
            defaultInstance = new ColInformation(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:databases.ColInformation)
    }

    public interface EntryOrBuilder extends com.google.protobuf.MessageOrBuilder {

        // repeated string information = 1;
        /**
         * <code>repeated string information = 1;</code>
         */
        java.util.List<java.lang.String> getInformationList();

        /**
         * <code>repeated string information = 1;</code>
         */
        int getInformationCount();

        /**
         * <code>repeated string information = 1;</code>
         */
        java.lang.String getInformation(int index);

        /**
         * <code>repeated string information = 1;</code>
         */
        com.google.protobuf.ByteString getInformationBytes(int index);
    }

    /**
     * Protobuf type {@code databases.Entry}
     */
    public static final class Entry extends com.google.protobuf.GeneratedMessage implements EntryOrBuilder {
        // Use Entry.newBuilder() to construct.
        private Entry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Entry(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final Entry defaultInstance;

        public static Entry getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public Entry getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Entry(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            information_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        information_.add(input.readBytes());
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    information_ = new com.google.protobuf.UnmodifiableLazyStringList(information_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.protocol.buffers.TabularStructure.internal_static_databases_Entry_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.protocol.buffers.TabularStructure.internal_static_databases_Entry_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.protocol.buffers.TabularStructure.Entry.class,
                            com.protocol.buffers.TabularStructure.Entry.Builder.class);
        }

        public static com.google.protobuf.Parser<Entry> PARSER = new com.google.protobuf.AbstractParser<Entry>() {
            @Override
            public Entry parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new Entry(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<Entry> getParserForType() {
            return PARSER;
        }

        // repeated string information = 1;
        public static final int INFORMATION_FIELD_NUMBER = 1;
        private com.google.protobuf.LazyStringList information_;

        /**
         * <code>repeated string information = 1;</code>
         */
        @Override
        public java.util.List<java.lang.String> getInformationList() {
            return information_;
        }

        /**
         * <code>repeated string information = 1;</code>
         */
        @Override
        public int getInformationCount() {
            return information_.size();
        }

        /**
         * <code>repeated string information = 1;</code>
         */
        @Override
        public java.lang.String getInformation(int index) {
            return information_.get(index);
        }

        /**
         * <code>repeated string information = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString getInformationBytes(int index) {
            return information_.getByteString(index);
        }

        private void initFields() {
            information_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < information_.size(); i++) {
                output.writeBytes(1, information_.getByteString(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < information_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(information_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getInformationList().size();
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.Entry parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.protocol.buffers.TabularStructure.Entry prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code databases.Entry}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.protocol.buffers.TabularStructure.EntryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_Entry_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_Entry_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.protocol.buffers.TabularStructure.Entry.class,
                                com.protocol.buffers.TabularStructure.Entry.Builder.class);
            }

            // Construct using
            // com.protocol.buffers.TabularStructure.Entry.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                information_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_Entry_descriptor;
            }

            @Override
            public com.protocol.buffers.TabularStructure.Entry getDefaultInstanceForType() {
                return com.protocol.buffers.TabularStructure.Entry.getDefaultInstance();
            }

            @Override
            public com.protocol.buffers.TabularStructure.Entry build() {
                com.protocol.buffers.TabularStructure.Entry result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.protocol.buffers.TabularStructure.Entry buildPartial() {
                com.protocol.buffers.TabularStructure.Entry result = new com.protocol.buffers.TabularStructure.Entry(
                        this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    information_ = new com.google.protobuf.UnmodifiableLazyStringList(information_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.information_ = information_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.protocol.buffers.TabularStructure.Entry) {
                    return mergeFrom((com.protocol.buffers.TabularStructure.Entry) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.protocol.buffers.TabularStructure.Entry other) {
                if (other == com.protocol.buffers.TabularStructure.Entry.getDefaultInstance())
                    return this;
                if (!other.information_.isEmpty()) {
                    if (information_.isEmpty()) {
                        information_ = other.information_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureInformationIsMutable();
                        information_.addAll(other.information_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.protocol.buffers.TabularStructure.Entry parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.protocol.buffers.TabularStructure.Entry) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // repeated string information = 1;
            private com.google.protobuf.LazyStringList information_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureInformationIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    information_ = new com.google.protobuf.LazyStringArrayList(information_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            @Override
            public java.util.List<java.lang.String> getInformationList() {
                return java.util.Collections.unmodifiableList(information_);
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            @Override
            public int getInformationCount() {
                return information_.size();
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            @Override
            public java.lang.String getInformation(int index) {
                return information_.get(index);
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString getInformationBytes(int index) {
                return information_.getByteString(index);
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            public Builder setInformation(int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureInformationIsMutable();
                information_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            public Builder addInformation(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureInformationIsMutable();
                information_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            public Builder addAllInformation(java.lang.Iterable<java.lang.String> values) {
                ensureInformationIsMutable();
                super.addAll(values, information_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            public Builder clearInformation() {
                information_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string information = 1;</code>
             */
            public Builder addInformationBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureInformationIsMutable();
                information_.add(value);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:databases.Entry)
        }

        static {
            defaultInstance = new Entry(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:databases.Entry)
    }

    public interface TableOrBuilder extends com.google.protobuf.MessageOrBuilder {

        // repeated .databases.ColInformation columns = 1;
        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        java.util.List<com.protocol.buffers.TabularStructure.ColInformation> getColumnsList();

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        com.protocol.buffers.TabularStructure.ColInformation getColumns(int index);

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        int getColumnsCount();

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        java.util.List<? extends com.protocol.buffers.TabularStructure.ColInformationOrBuilder> getColumnsOrBuilderList();

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        com.protocol.buffers.TabularStructure.ColInformationOrBuilder getColumnsOrBuilder(int index);

        // repeated .databases.Entry entry = 2;
        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        java.util.List<com.protocol.buffers.TabularStructure.Entry> getEntryList();

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        com.protocol.buffers.TabularStructure.Entry getEntry(int index);

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        int getEntryCount();

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        java.util.List<? extends com.protocol.buffers.TabularStructure.EntryOrBuilder> getEntryOrBuilderList();

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        com.protocol.buffers.TabularStructure.EntryOrBuilder getEntryOrBuilder(int index);
    }

    /**
     * Protobuf type {@code databases.Table}
     */
    public static final class Table extends com.google.protobuf.GeneratedMessage implements TableOrBuilder {
        // Use Table.newBuilder() to construct.
        private Table(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Table(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final Table defaultInstance;

        public static Table getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public Table getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Table(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            columns_ = new java.util.ArrayList<com.protocol.buffers.TabularStructure.ColInformation>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        columns_.add(input.readMessage(com.protocol.buffers.TabularStructure.ColInformation.PARSER,
                                extensionRegistry));
                        break;
                    }
                    case 18: {
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            entry_ = new java.util.ArrayList<com.protocol.buffers.TabularStructure.Entry>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        entry_.add(input.readMessage(com.protocol.buffers.TabularStructure.Entry.PARSER,
                                extensionRegistry));
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    columns_ = java.util.Collections.unmodifiableList(columns_);
                }
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    entry_ = java.util.Collections.unmodifiableList(entry_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.protocol.buffers.TabularStructure.internal_static_databases_Table_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.protocol.buffers.TabularStructure.internal_static_databases_Table_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.protocol.buffers.TabularStructure.Table.class,
                            com.protocol.buffers.TabularStructure.Table.Builder.class);
        }

        public static com.google.protobuf.Parser<Table> PARSER = new com.google.protobuf.AbstractParser<Table>() {
            @Override
            public Table parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new Table(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<Table> getParserForType() {
            return PARSER;
        }

        // repeated .databases.ColInformation columns = 1;
        public static final int COLUMNS_FIELD_NUMBER = 1;
        private java.util.List<com.protocol.buffers.TabularStructure.ColInformation> columns_;

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        @Override
        public java.util.List<com.protocol.buffers.TabularStructure.ColInformation> getColumnsList() {
            return columns_;
        }

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        @Override
        public java.util.List<? extends com.protocol.buffers.TabularStructure.ColInformationOrBuilder> getColumnsOrBuilderList() {
            return columns_;
        }

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        @Override
        public int getColumnsCount() {
            return columns_.size();
        }

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        @Override
        public com.protocol.buffers.TabularStructure.ColInformation getColumns(int index) {
            return columns_.get(index);
        }

        /**
         * <code>repeated .databases.ColInformation columns = 1;</code>
         */
        @Override
        public com.protocol.buffers.TabularStructure.ColInformationOrBuilder getColumnsOrBuilder(int index) {
            return columns_.get(index);
        }

        // repeated .databases.Entry entry = 2;
        public static final int ENTRY_FIELD_NUMBER = 2;
        private java.util.List<com.protocol.buffers.TabularStructure.Entry> entry_;

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        @Override
        public java.util.List<com.protocol.buffers.TabularStructure.Entry> getEntryList() {
            return entry_;
        }

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        @Override
        public java.util.List<? extends com.protocol.buffers.TabularStructure.EntryOrBuilder> getEntryOrBuilderList() {
            return entry_;
        }

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        @Override
        public int getEntryCount() {
            return entry_.size();
        }

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        @Override
        public com.protocol.buffers.TabularStructure.Entry getEntry(int index) {
            return entry_.get(index);
        }

        /**
         * <code>repeated .databases.Entry entry = 2;</code>
         */
        @Override
        public com.protocol.buffers.TabularStructure.EntryOrBuilder getEntryOrBuilder(int index) {
            return entry_.get(index);
        }

        private void initFields() {
            columns_ = java.util.Collections.emptyList();
            entry_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < columns_.size(); i++) {
                output.writeMessage(1, columns_.get(i));
            }
            for (int i = 0; i < entry_.size(); i++) {
                output.writeMessage(2, entry_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            for (int i = 0; i < columns_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, columns_.get(i));
            }
            for (int i = 0; i < entry_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, entry_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Table parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.Table parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.protocol.buffers.TabularStructure.Table parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.protocol.buffers.TabularStructure.Table prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code databases.Table}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.protocol.buffers.TabularStructure.TableOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_Table_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_Table_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.protocol.buffers.TabularStructure.Table.class,
                                com.protocol.buffers.TabularStructure.Table.Builder.class);
            }

            // Construct using
            // com.protocol.buffers.TabularStructure.Table.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getColumnsFieldBuilder();
                    getEntryFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                if (columnsBuilder_ == null) {
                    columns_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    columnsBuilder_.clear();
                }
                if (entryBuilder_ == null) {
                    entry_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    entryBuilder_.clear();
                }
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.protocol.buffers.TabularStructure.internal_static_databases_Table_descriptor;
            }

            @Override
            public com.protocol.buffers.TabularStructure.Table getDefaultInstanceForType() {
                return com.protocol.buffers.TabularStructure.Table.getDefaultInstance();
            }

            @Override
            public com.protocol.buffers.TabularStructure.Table build() {
                com.protocol.buffers.TabularStructure.Table result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.protocol.buffers.TabularStructure.Table buildPartial() {
                com.protocol.buffers.TabularStructure.Table result = new com.protocol.buffers.TabularStructure.Table(
                        this);
                int from_bitField0_ = bitField0_;
                if (columnsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        columns_ = java.util.Collections.unmodifiableList(columns_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.columns_ = columns_;
                } else {
                    result.columns_ = columnsBuilder_.build();
                }
                if (entryBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        entry_ = java.util.Collections.unmodifiableList(entry_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.entry_ = entry_;
                } else {
                    result.entry_ = entryBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.protocol.buffers.TabularStructure.Table) {
                    return mergeFrom((com.protocol.buffers.TabularStructure.Table) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.protocol.buffers.TabularStructure.Table other) {
                if (other == com.protocol.buffers.TabularStructure.Table.getDefaultInstance())
                    return this;
                if (columnsBuilder_ == null) {
                    if (!other.columns_.isEmpty()) {
                        if (columns_.isEmpty()) {
                            columns_ = other.columns_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureColumnsIsMutable();
                            columns_.addAll(other.columns_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.columns_.isEmpty()) {
                        if (columnsBuilder_.isEmpty()) {
                            columnsBuilder_.dispose();
                            columnsBuilder_ = null;
                            columns_ = other.columns_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            columnsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                    ? getColumnsFieldBuilder() : null;
                        } else {
                            columnsBuilder_.addAllMessages(other.columns_);
                        }
                    }
                }
                if (entryBuilder_ == null) {
                    if (!other.entry_.isEmpty()) {
                        if (entry_.isEmpty()) {
                            entry_ = other.entry_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureEntryIsMutable();
                            entry_.addAll(other.entry_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.entry_.isEmpty()) {
                        if (entryBuilder_.isEmpty()) {
                            entryBuilder_.dispose();
                            entryBuilder_ = null;
                            entry_ = other.entry_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                            entryBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                    ? getEntryFieldBuilder() : null;
                        } else {
                            entryBuilder_.addAllMessages(other.entry_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.protocol.buffers.TabularStructure.Table parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.protocol.buffers.TabularStructure.Table) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // repeated .databases.ColInformation columns = 1;
            private java.util.List<com.protocol.buffers.TabularStructure.ColInformation> columns_ = java.util.Collections
                    .emptyList();

            private void ensureColumnsIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    columns_ = new java.util.ArrayList<com.protocol.buffers.TabularStructure.ColInformation>(columns_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.protocol.buffers.TabularStructure.ColInformation, com.protocol.buffers.TabularStructure.ColInformation.Builder, com.protocol.buffers.TabularStructure.ColInformationOrBuilder> columnsBuilder_;

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            @Override
            public java.util.List<com.protocol.buffers.TabularStructure.ColInformation> getColumnsList() {
                if (columnsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(columns_);
                } else {
                    return columnsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            @Override
            public int getColumnsCount() {
                if (columnsBuilder_ == null) {
                    return columns_.size();
                } else {
                    return columnsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            @Override
            public com.protocol.buffers.TabularStructure.ColInformation getColumns(int index) {
                if (columnsBuilder_ == null) {
                    return columns_.get(index);
                } else {
                    return columnsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder setColumns(int index, com.protocol.buffers.TabularStructure.ColInformation value) {
                if (columnsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureColumnsIsMutable();
                    columns_.set(index, value);
                    onChanged();
                } else {
                    columnsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder setColumns(int index,
                    com.protocol.buffers.TabularStructure.ColInformation.Builder builderForValue) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    columnsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder addColumns(com.protocol.buffers.TabularStructure.ColInformation value) {
                if (columnsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureColumnsIsMutable();
                    columns_.add(value);
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder addColumns(int index, com.protocol.buffers.TabularStructure.ColInformation value) {
                if (columnsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureColumnsIsMutable();
                    columns_.add(index, value);
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder addColumns(com.protocol.buffers.TabularStructure.ColInformation.Builder builderForValue) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.add(builderForValue.build());
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder addColumns(int index,
                    com.protocol.buffers.TabularStructure.ColInformation.Builder builderForValue) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    columnsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder addAllColumns(
                    java.lang.Iterable<? extends com.protocol.buffers.TabularStructure.ColInformation> values) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    super.addAll(values, columns_);
                    onChanged();
                } else {
                    columnsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder clearColumns() {
                if (columnsBuilder_ == null) {
                    columns_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    columnsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public Builder removeColumns(int index) {
                if (columnsBuilder_ == null) {
                    ensureColumnsIsMutable();
                    columns_.remove(index);
                    onChanged();
                } else {
                    columnsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public com.protocol.buffers.TabularStructure.ColInformation.Builder getColumnsBuilder(int index) {
                return getColumnsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            @Override
            public com.protocol.buffers.TabularStructure.ColInformationOrBuilder getColumnsOrBuilder(int index) {
                if (columnsBuilder_ == null) {
                    return columns_.get(index);
                } else {
                    return columnsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            @Override
            public java.util.List<? extends com.protocol.buffers.TabularStructure.ColInformationOrBuilder> getColumnsOrBuilderList() {
                if (columnsBuilder_ != null) {
                    return columnsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(columns_);
                }
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public com.protocol.buffers.TabularStructure.ColInformation.Builder addColumnsBuilder() {
                return getColumnsFieldBuilder()
                        .addBuilder(com.protocol.buffers.TabularStructure.ColInformation.getDefaultInstance());
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public com.protocol.buffers.TabularStructure.ColInformation.Builder addColumnsBuilder(int index) {
                return getColumnsFieldBuilder().addBuilder(index,
                        com.protocol.buffers.TabularStructure.ColInformation.getDefaultInstance());
            }

            /**
             * <code>repeated .databases.ColInformation columns = 1;</code>
             */
            public java.util.List<com.protocol.buffers.TabularStructure.ColInformation.Builder> getColumnsBuilderList() {
                return getColumnsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.protocol.buffers.TabularStructure.ColInformation, com.protocol.buffers.TabularStructure.ColInformation.Builder, com.protocol.buffers.TabularStructure.ColInformationOrBuilder> getColumnsFieldBuilder() {
                if (columnsBuilder_ == null) {
                    columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.protocol.buffers.TabularStructure.ColInformation, com.protocol.buffers.TabularStructure.ColInformation.Builder, com.protocol.buffers.TabularStructure.ColInformationOrBuilder>(
                            columns_, ((bitField0_ & 0x00000001) == 0x00000001), getParentForChildren(), isClean());
                    columns_ = null;
                }
                return columnsBuilder_;
            }

            // repeated .databases.Entry entry = 2;
            private java.util.List<com.protocol.buffers.TabularStructure.Entry> entry_ = java.util.Collections
                    .emptyList();

            private void ensureEntryIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    entry_ = new java.util.ArrayList<com.protocol.buffers.TabularStructure.Entry>(entry_);
                    bitField0_ |= 0x00000002;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.protocol.buffers.TabularStructure.Entry, com.protocol.buffers.TabularStructure.Entry.Builder, com.protocol.buffers.TabularStructure.EntryOrBuilder> entryBuilder_;

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            @Override
            public java.util.List<com.protocol.buffers.TabularStructure.Entry> getEntryList() {
                if (entryBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(entry_);
                } else {
                    return entryBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            @Override
            public int getEntryCount() {
                if (entryBuilder_ == null) {
                    return entry_.size();
                } else {
                    return entryBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            @Override
            public com.protocol.buffers.TabularStructure.Entry getEntry(int index) {
                if (entryBuilder_ == null) {
                    return entry_.get(index);
                } else {
                    return entryBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder setEntry(int index, com.protocol.buffers.TabularStructure.Entry value) {
                if (entryBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureEntryIsMutable();
                    entry_.set(index, value);
                    onChanged();
                } else {
                    entryBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder setEntry(int index, com.protocol.buffers.TabularStructure.Entry.Builder builderForValue) {
                if (entryBuilder_ == null) {
                    ensureEntryIsMutable();
                    entry_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    entryBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder addEntry(com.protocol.buffers.TabularStructure.Entry value) {
                if (entryBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureEntryIsMutable();
                    entry_.add(value);
                    onChanged();
                } else {
                    entryBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder addEntry(int index, com.protocol.buffers.TabularStructure.Entry value) {
                if (entryBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureEntryIsMutable();
                    entry_.add(index, value);
                    onChanged();
                } else {
                    entryBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder addEntry(com.protocol.buffers.TabularStructure.Entry.Builder builderForValue) {
                if (entryBuilder_ == null) {
                    ensureEntryIsMutable();
                    entry_.add(builderForValue.build());
                    onChanged();
                } else {
                    entryBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder addEntry(int index, com.protocol.buffers.TabularStructure.Entry.Builder builderForValue) {
                if (entryBuilder_ == null) {
                    ensureEntryIsMutable();
                    entry_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    entryBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder addAllEntry(
                    java.lang.Iterable<? extends com.protocol.buffers.TabularStructure.Entry> values) {
                if (entryBuilder_ == null) {
                    ensureEntryIsMutable();
                    super.addAll(values, entry_);
                    onChanged();
                } else {
                    entryBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder clearEntry() {
                if (entryBuilder_ == null) {
                    entry_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    entryBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public Builder removeEntry(int index) {
                if (entryBuilder_ == null) {
                    ensureEntryIsMutable();
                    entry_.remove(index);
                    onChanged();
                } else {
                    entryBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public com.protocol.buffers.TabularStructure.Entry.Builder getEntryBuilder(int index) {
                return getEntryFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            @Override
            public com.protocol.buffers.TabularStructure.EntryOrBuilder getEntryOrBuilder(int index) {
                if (entryBuilder_ == null) {
                    return entry_.get(index);
                } else {
                    return entryBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            @Override
            public java.util.List<? extends com.protocol.buffers.TabularStructure.EntryOrBuilder> getEntryOrBuilderList() {
                if (entryBuilder_ != null) {
                    return entryBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(entry_);
                }
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public com.protocol.buffers.TabularStructure.Entry.Builder addEntryBuilder() {
                return getEntryFieldBuilder()
                        .addBuilder(com.protocol.buffers.TabularStructure.Entry.getDefaultInstance());
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public com.protocol.buffers.TabularStructure.Entry.Builder addEntryBuilder(int index) {
                return getEntryFieldBuilder().addBuilder(index,
                        com.protocol.buffers.TabularStructure.Entry.getDefaultInstance());
            }

            /**
             * <code>repeated .databases.Entry entry = 2;</code>
             */
            public java.util.List<com.protocol.buffers.TabularStructure.Entry.Builder> getEntryBuilderList() {
                return getEntryFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.protocol.buffers.TabularStructure.Entry, com.protocol.buffers.TabularStructure.Entry.Builder, com.protocol.buffers.TabularStructure.EntryOrBuilder> getEntryFieldBuilder() {
                if (entryBuilder_ == null) {
                    entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.protocol.buffers.TabularStructure.Entry, com.protocol.buffers.TabularStructure.Entry.Builder, com.protocol.buffers.TabularStructure.EntryOrBuilder>(
                            entry_, ((bitField0_ & 0x00000002) == 0x00000002), getParentForChildren(), isClean());
                    entry_ = null;
                }
                return entryBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:databases.Table)
        }

        static {
            defaultInstance = new Table(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:databases.Table)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_databases_ColInformation_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_databases_ColInformation_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_databases_Entry_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_databases_Entry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_databases_Table_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_databases_Table_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = { "\n\025protocolBuffers.proto\022\tdatabases\"2\n\016Co"
                + "lInformation\022\017\n\007colName\030\001 \001(\t\022\017\n\007colType"
                + "\030\002 \001(\t\"\034\n\005Entry\022\023\n\013information\030\001 \003(\t\"T\n\005"
                + "Table\022*\n\007columns\030\001 \003(\0132\031.databases.ColIn"
                + "formation\022\037\n\005entry\030\002 \003(\0132\020.databases.Ent"
                + "ryB(\n\024com.protocol.buffersB\020TabularStruc" + "ture" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            @Override
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_databases_ColInformation_descriptor = getDescriptor().getMessageTypes().get(0);
                internal_static_databases_ColInformation_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_databases_ColInformation_descriptor,
                        new java.lang.String[] { "ColName", "ColType", });
                internal_static_databases_Entry_descriptor = getDescriptor().getMessageTypes().get(1);
                internal_static_databases_Entry_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_databases_Entry_descriptor, new java.lang.String[] { "Information", });
                internal_static_databases_Table_descriptor = getDescriptor().getMessageTypes().get(2);
                internal_static_databases_Table_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_databases_Table_descriptor, new java.lang.String[] { "Columns", "Entry", });
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
